### ISSUE TITLE
module/loading appears unused

### ISSUE THREAD

**Issue by andrewchambers** [janet-lang/path#3]
Sorry if this is a mistake on my part:

```
[ac@black:~/src/janet]$ git grep "module/loading"
src/boot/boot.janet:(def module/loading
src/boot/boot.janet:              (put module/loading path true)
src/boot/boot.janet:              (put module/loading path nil)
```

This table appears to serve no purpose.

**Comment by bakpakin** [comment]
This is for detecting circular dependencies. One could argue that it doesn’t need to be exposed, but it does not hurt.

**Comment by bakpakin** [comment]
Also, wrong repo?

**Comment by bakpakin** [comment]
Also, wrong repo?

**Comment by andrewchambers** [comment]
Im confused, how does it it detect circular dependencies if it is never used?

**Comment by andrewchambers** [comment]
Oh sorry wrong repo.
